package com.refuge.next.data

import org.json.JSONObject
import kotlin.math.*

internal data class ErkulMetrics(
    val burst: Double, val sustained: Double, val pilotBurst: Double, val shield: Double,
    val shieldRegen: Double, val power: Double, val powerUsed: Double, val cooling: Double,
    val coolingUsed: Double, val mass: Double, val quantumSpeed: Double?, val quantumRange: Double?,
    val weaponPool: Double, val weaponDemand: Double,
)

internal fun resourceUnits(item: JSONObject, output: Boolean, resource: String, unit: String? = null): Double {
    val online = item.obj("resource").objects("states").firstOrNull { it.optString("name") == "Online" } ?: return 0.0
    return online.objects("flows").flatMap { it.objects(if (output) "produces" else "consumes") }
        .filter { it.optString("resource") == resource && (unit == null || it.optString("unitKind") == unit) }
        .sumOf { it.number("units") ?: 0.0 }
}

internal fun weaponBurst(item: JSONObject): Double {
    val weapon = item.obj("weapon")
    val damage = weapon.obj("ammo").obj("damage")
    val alpha = damage.keys().asSequence().sumOf { damage.number(it) ?: 0.0 }
    val fire = weapon.objects("fireActions").firstOrNull { (it.number("fireRate") ?: 0.0) > 0 } ?: return 0.0
    return alpha * (fire.number("fireRate") ?: 0.0) / 60.0 * (fire.number("pelletCount") ?: 1.0) * (fire.number("damageMultiplier") ?: 1.0)
}

/** Erkul's capacitor cycle: firing duration + regeneration delay + full recharge duration. */
internal fun weaponSustained(item: JSONObject, poolRatio: Double): Double {
    val weapon = item.obj("weapon")
    val burst = weaponBurst(item)
    val fire = weapon.objects("fireActions").firstOrNull { (it.number("fireRate") ?: 0.0) > 0 } ?: return 0.0
    val rate = (fire.number("fireRate") ?: 0.0) / 60.0
    val regen = weapon.optJSONObject("regen")
    var fireTime = Double.POSITIVE_INFINITY
    var charge = 0.0
    if (regen != null) {
        val bullets = floor((regen.number("maxAmmoLoad") ?: 0.0) * poolRatio + .5)
        val refill = (regen.number("maxRegenPerSec") ?: 0.0) * poolRatio
        if (bullets <= 0 || refill <= 0 || rate <= 0) return 0.0
        fireTime = bullets / rate
        charge = (regen.number("regenerationCooldown") ?: 0.0) + bullets / refill
    }
    val heat = weapon.obj("connection").optJSONObject("heat")
    if (heat != null && (fire.number("heatPerShot") ?: 0.0) > 0) {
        val heatRate = fire.getDouble("heatPerShot") * rate
        val window = (heat.number("overheatTemperature") ?: 0.0) - (heat.number("temperatureAfterOverheatFix") ?: 0.0)
        if (window > 0) {
            val overheat = window / heatRate
            if (overheat < fireTime) return burst * overheat / (overheat + (heat.number("overheatFixTime") ?: 0.0))
        }
    }
    return if (fireTime.isInfinite()) burst else burst * fireTime / (fireTime + charge)
}

/**
 * Heat is represented by two different fields in the Erkul data set.  Items
 * that radiate heat while online expose `connection.heatRateOnline`; weapons
 * normally expose heat per shot on their fire action instead.  Keeping this
 * conversion here makes the performance sheet useful even when no component
 * has an explicit Coolant consume flow (which is the common case for weapons).
 */
internal fun heatGenerationPerSecond(item: JSONObject): Double {
    val weapon = item.obj("weapon")
    val connection = weapon.obj("connection")
    val online = connection.number("heatRateOnline") ?: 0.0
    val firing = weapon.objects("fireActions").sumOf { action ->
        val heatPerShot = action.number("heatPerShot") ?: 0.0
        val fireRate = action.number("fireRate") ?: 0.0
        val pellets = (action.number("pelletCount") ?: 1.0).coerceAtLeast(1.0)
        if (heatPerShot > 0.0 && fireRate > 0.0) heatPerShot * fireRate / 60.0 * pellets else 0.0
    }
    return (online + firing).coerceAtLeast(0.0)
}

/** Sum coolant consumed by a component and heat that must be removed per sec. */
internal fun coolingDemandPerSecond(item: JSONObject, powerRatio: Double): Double {
    if (powerRatio <= 0.0) return 0.0
    val coolant = resourceUnits(item, output = false, resource = "Coolant")
    return (coolant + heatGenerationPerSecond(item)) * powerRatio
}

/** Coolant generated by a powered convert flow, in Erkul's rating units. */
internal fun coolingGenerationPerSecond(item: JSONObject, powerRatio: Double): Double {
    if (powerRatio <= 0.0) return 0.0
    val generated = resourceUnits(item, output = true, resource = "Coolant")
    return generated * powerRatio
}

internal fun calculateErkulMetrics(ship: JSONObject, slots: List<ErkulSlot>, draft: JSONObject): ErkulMetrics {
    val active = activeErkulSlots(slots, draft)
    val allocation = allocateErkulPower(ship, slots, draft)
    val weapons = active.filter { it.item!!.optString("type") == "WeaponGun" && draft.optString("flightMode") != "NAV" }
    // The rendered capacity follows Erkul's multi-generator distribution
    // model, rather than summing the raw output of every generator.
    val power = allocation.capacity.toDouble()
    val fixedPool = ship.obj("vehicle").obj("powerPools").objects("pools")
        .firstOrNull { it.optString("itemType") == "WeaponGun" }?.number("poolSize") ?: 0.0
    val demand = ceil(weapons.sumOf { resourceUnits(it.item!!, false, "Power") })
    val pool = allocation.supplied("weapons").toDouble()
    val ratio = if (demand <= 0) 1.0 else min(1.0, pool / demand)
    val cooling = active.sumOf { slot ->
        val item = slot.item!!
        val itemRatio = if (item.optString("type") == "WeaponGun") ratio
        else powerOutputRatio(item, allocation.supplied(slot.path))
        coolingGenerationPerSecond(item, itemRatio)
    }
    val coolingUsed = active.sumOf { slot ->
        val item = slot.item!!
        val itemRatio = if (item.optString("type") == "WeaponGun") ratio
        else powerOutputRatio(item, allocation.supplied(slot.path))
        coolingDemandPerSecond(item, itemRatio)
    }
    val quantum = active.firstOrNull { it.item!!.has("qdrive") }?.item?.obj("qdrive")
    val fuel = ship.obj("precomputed").obj("fuel").number("quantumCapacity")
    val burn = quantum?.number("quantumFuelRequirement")
    return ErkulMetrics(
        burst = weapons.sumOf { weaponBurst(it.item!!) },
        sustained = weapons.sumOf { weaponSustained(it.item!!, ratio) },
        pilotBurst = weapons.filter { it.pilot }.sumOf { weaponBurst(it.item!!) },
        shield = active.filter { allocation.supplied(it.path) > 0 }.sumOf { it.item!!.obj("shield").number("maxShieldHealth") ?: 0.0 },
        shieldRegen = active.sumOf { (it.item!!.obj("shield").number("maxShieldRegen") ?: 0.0) * powerOutputRatio(it.item, allocation.supplied(it.path)) },
        power = power,
        powerUsed = allocation.used.toDouble(),
        cooling = cooling,
        coolingUsed = coolingUsed,
        mass = (ship.obj("precomputed").number("massFixedKg") ?: 0.0) + slots.mapNotNull { it.item }.sumOf { it.number("mass") ?: 0.0 },
        quantumSpeed = quantum?.obj("params")?.number("driveSpeed"),
        quantumRange = if (fuel != null && burn != null && burn > 0) fuel / burn else null,
        weaponPool = fixedPool, weaponDemand = demand,
    )
}
